GET http://localhost:5001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKdW5pbmRpIiwiZW1haWwiOiJmZXJ0YTIzQGdtYWlsLmNvbSIsImlhdCI6MTczMzk5MDM0NCwiZXhwIjoxNzMzOTkwNDA0fQ.t2h58rUYI8wBTTYoFHzXUHosj37gZAOgjsF5wlkBajc
###
POST  http://localhost:5001/users
Content-Type: application/json

{
    "name" : "Junindi",
    "email" : "ferta23@gmail.com",
    "password" : "ferta123",
    "confPassword" : "ferta123"
}

###
POST  http://localhost:5001/login
Content-Type: application/json

{
    "email" : "ferta23@gmail.com",
    "password" : "ferta123"
}

###
POST  http://localhost:5001/token

###
DELETE  http://localhost:5001/logout

